name: "Ankit Kumar GitHub"
on:
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**' 

jobs:
  terraformInit:
    name: Terraform Init
    runs-on: [self-hosted, Ankit-Kumar]  # Corrected line
    steps:
    - name: First Step
      run: echo "Hello World from Ankit-Kumar Runner"
